name: CI testing

on:
  push:
    branches: [main, refactor/cicd]
  pull_request:
    branches: [main]

jobs:
  run-ci-testing:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check Go
        run: go version

      - name: Build & start containers
        run: docker compose up -d --build

      - name: Run tests
        run: go test -v ./test

      - name: Cleanup
        if: always()
        run: docker compose down -v