name: CI testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-ci-testing:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Go
        run: go version

      - name: Decrypt .env
        run: |
          echo "${{ secrets.SOPS_AGE_KEY }}" > age.key
          sops --decrypt --input-type dotenv --output-type dotenv --output .env dev.enc
        env:
          SOPS_AGE_KEY_FILE: age.key

      - name: Start containers
        run: docker compose up -d

      - name: Build Go application
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
